Update pipeline

diff --git a/pipeline b/pipeline
--- a/pipeline
+++ b/pipeline
@@ -5,48 +5,46 @@ pool:
 steps:
 - script: |
     #!/bin/bash
-    ORG="xx"
-    PER_PAGE=100
-    OUTPUT_FILE="admins.csv"
+    GITHUB_API_URL="https://api.github.com"
+    ORG_NAME="inc"
+    OUTPUT_FILE="org_user_access.csv"
 
-    fetch_repos_page() {
-      local page=$1
-      curl -s -H "Authorization: token $(TOKEN)" \
-        "https://api.github.com/orgs/$ORG/repos?per_page=$PER_PAGE&page=$page" | jq -r '.[].name'
+    if ! command -v jq &>/dev/null; then
+        echo "Error: jq is not installed. Please install jq and try again."
+        exit 1
+    fi
+
+    echo "Repository,Username,Access Level" > "$OUTPUT_FILE"
+
+    fetch_repos() {
+        curl -s -H "Authorization: token $(TOKEN)" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "$GITHUB_API_URL/orgs/$ORG_NAME/repos?per_page=100&page=$1"
     }
 
-    get_admins() {
-      local repo=$1
-      curl -s -H "Authorization: token $(TOKEN)" \
-        "https://api.github.com/repos/$ORG/$repo/collaborators?per_page=100" | \
-        jq -r '.[] | select(.permissions.admin == true) | [.login, .html_url] | @csv'
+
+    fetch_collaborators() {
+        curl -s -H "Authorization: token $(TOKEN)" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "$GITHUB_API_URL/repos/$ORG_NAME/$1/collaborators"
     }
 
-    echo "Fetching all repositories from the organization $ORG..."
-    repos=()
     page=1
-    while : ; do
-      repos_page=($(fetch_repos_page $page))
-      if [ ${#repos_page[@]} -eq 0 ]; then
-        break
-      fi
-      repos+=("${repos_page[@]}")
-      page=$((page + 1))
-    done
+    while true; do
+        repos=$(fetch_repos "$page")
+        repo_count=$(echo "$repos" | jq '. | length')
 
-    # Fetch admin collaborators for each repository and save to CSV
-    echo "username,url" > "$OUTPUT_FILE"
-    for repo in "${repos[@]}"
-    do
-      echo "Processing repository $repo..."
-      get_admins "$repo" >> "$OUTPUT_FILE"
-    done
 
-    echo "Admins for all repositories in $ORG have been saved to $OUTPUT_FILE."
+        if [ "$repo_count" -eq 0 ]; then
+            break
+        fi
+
+        echo "$repos" | jq -r '.[].name' | while read -r repo; do
+        echo "Processing repository: $
 
 - task: PublishPipelineArtifact@1
   inputs:
-    targetPath: '$(System.DefaultWorkingDirectory)/admins.csv'
+    targetPath: '$(System.DefaultWorkingDirectory)/org_user_access.csv'
     artifact: 'myArtifacts'
     publishLocation: pipeline
   displayName: 'Publish Artifacts'
